appname: "Testapp"

charset: "UTF-8"

logger: "console"
log_level: "debug"
warnings: 1

public: t/testapp/public

engines:
    template:
        template_toolkit:
            ENCODING: utf8
            DEFAULT: 'no.tt'
template: "template_toolkit"

session: YAML

plugins:
  DBIC:
    default:
      dsn: dbi:SQLite:dbname=t/testapp/test.sqlite
      #dsn: dbi:SQLite:dbname=test.sqlite
      schema_class: TestDB

Strehler:
    admin_secured: 0
    languages: ['it', 'en']
    default_language: 'it'
    timezone: 'Europe/Rome'
    extra_menu:
        rsschannel:
            label: RSS
            class: Strehler::Element::RSS::RSSChannel
            auto: 1

